#!/usr/bin/env python3
"""Generate `x86_tests.mm0`, the spec test suite's contract, from `manifest.py`.

    ./gen.py            rewrite x86_tests.mm0, gen/cases.inc, gen/disasm.expected
    ./gen.py --check    fail (with a diff) if a committed file is stale

`gen/cases.inc` is the same manifest as a C table, for the runtime harness.  The
harness reads expectations, it never recomputes them: a recomputation would be a
second implementation of the semantics and would eventually reproduce the same
bug in both places.  So the register values a test does not name are filled in
here, and "unchanged" is expanded here into a mask the harness merely applies.

The `.mm0` carries one theorem *statement* per test and nothing else.  The
proofs live in the hand-written `x86_tests.mm1`, and `mm0-c` is what ties the
two together, so this generator never has to be trusted: if it emits the wrong
statement, the proofs stop discharging it.

Two things it does have to get right, because mm0-c's diagnostics for them are
unhelpful:

  * **Declaration order** must match the `.mmb`, i.e. manifest order must match
    the order of the proofs in the `.mm1`.  A mismatch reports `variable type
    does not match theorem` against the *following* declaration.
  * **Bound variables come first** in the binder list.  `E. k2` in the
    conclusion makes `k2` bound, so the binders read `{k2: nat} (k rip: nat)`.
    Getting this wrong reports `variable type does not match theorem` with the
    variables shifted by one.

Literals are written the way `peano_hex.mm1`'s `,0x...` / `,"..."` splices
elaborate them, since the terms have to be identical, not merely equal:

  * a nat is a `:x` chain of hex digits with no leading zeros (`hex` is public
    in `peano_hex.mm0` precisely so a contract can name 64 bit constants);
  * a nonempty byte string ends in `s1 c`, not `c ': s0` -- these are different
    string terms.
"""

import argparse
import difflib
import sys
import textwrap
from pathlib import Path

import manifest as M

HERE = Path(__file__).resolve().parent
MM0 = HERE / "x86_tests.mm0"
CASES = HERE / "gen" / "cases.inc"
DISASM = HERE / "gen" / "disasm.expected"

WIDTH = 78

PREAMBLE = """\
-- GENERATED by gen.py from manifest.py -- do not edit.
--
-- Declaration order is manifest order, and x86_tests.mm1 must follow it: mm0-c
-- requires the .mm0 and the .mmb to agree on relative order, and the error when
-- they do not points at the *following* declaration.
"""

IMPORT = 'import "../../examples/compiler.mm0";'


# ---------------------------------------------------------------------------
# Literals
# ---------------------------------------------------------------------------

def mm0_nat(n: int) -> str:
    """A nat literal, as `,0x...` elaborates it: `x4 :x xf`, `x1`, `x0`."""
    assert n >= 0
    return " :x ".join("x" + d for d in format(n, "x"))


def mm0_char(b: int) -> str:
    assert 0 <= b < 256
    return "ch x%x x%x" % (b >> 4, b & 0xf)


def mm0_string(code) -> str:
    """A byte string, as `,"..."` elaborates it: an `s1` tail, never `': s0`."""
    if not code:
        return "s0"
    chars = [mm0_char(b) for b in code]
    return "".join(c + " ': " for c in chars[:-1]) + "s1 (%s)" % chars[-1]


# ---------------------------------------------------------------------------
# Statements
# ---------------------------------------------------------------------------

def clause(c) -> str:
    if isinstance(c, M.Reg):
        return "readReg k2 %s = %s" % (c.reg, mm0_nat(c.value))
    if isinstance(c, M.RegsSame):
        return "readReg k2 r = readReg k r"
    if isinstance(c, M.FlagsSame):
        return "readFlags k2 = readFlags k"
    if isinstance(c, M.Flag):
        return "%s (readFlags k2)" % c.flag if c.on else "~%s (readFlags k2)" % c.flag
    if isinstance(c, M.FlagSame):
        return "(%s (readFlags k2) <-> %s (readFlags k))" % (c.flag, c.flag)
    raise TypeError("unknown post-state clause: %r" % (c,))


def hypotheses(t):
    """`(label, statement)` pairs, in binder order."""
    hs = [
        ("hk", "k e. Config"),
        ("hex", "readException k = 0"),
        ("hc", "readMemX k (readRIP k) (%s)" % mm0_string(t.code)),
        ("hrip", "readRIP k = rip"),
    ]
    hs += [("h" + reg.lower(), "readReg k %s = %s" % (reg, mm0_nat(v)))
           for reg, v in t.pre]
    return hs


def render(t) -> str:
    out = ["--| " + l for l in textwrap.wrap(t.doc, WIDTH - 4)]

    # `r` is only in scope if some clause is stated at a symbolic register.
    free = "k rip r" if any(isinstance(c, M.RegsSame) for c in t.post) else "k rip"
    out.append("theorem %s {k2: nat} (%s: nat)" % (t.name, free))

    hs = hypotheses(t)
    pad = max(len(lbl) for lbl, _ in hs) + 1
    for lbl, stmt in hs:
        out.append("  (%s $ %s $)" % ((lbl + ":").ljust(pad), stmt))
    out[-1] += ":"  # the binder list ends here; the conclusion follows

    body = ["step k k2", "readRIP k2 = rip +_64 %d" % len(t.code)]
    body += [clause(c) for c in t.post]
    out.append("  $ E. k2 (" + body[0] + " /\\")
    out += ["      " + c + " /\\" for c in body[1:-1]]
    out.append("      " + body[-1] + ") $;")
    return "\n".join(out)


def index() -> str:
    """A table of what is being tested, keyed the way a reader wants it."""
    w = max(len(t.name) for t in M.TESTS)
    c = max(len(" ".join("%02x" % b for b in t.code)) for t in M.TESTS)
    rows = ["--   %s  %s  %s" % (t.name.ljust(w),
                                 " ".join("%02x" % b for b in t.code).ljust(c),
                                 t.disasm)
            for t in M.TESTS]
    return "\n".join(["-- Tests, in declaration order:"] + rows)


def generate_mm0() -> str:
    parts = [PREAMBLE, index(), "", IMPORT]
    for t in M.TESTS:
        parts += ["", render(t)]
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# gen/cases.inc
# ---------------------------------------------------------------------------

C_PREAMBLE = """\
/* GENERATED by gen.py from manifest.py -- do not edit.
 *
 * One row per test, in the same order as x86_tests.mm0.  Every value here comes
 * from the manifest; the harness applies them and compares, and computes nothing
 * about what the instruction does.
 *
 * `reg_in` is the state to load.  A register a test does not name gets a filler
 * pattern rather than zero, so that a `regs unchanged` assertion is a real
 * check and a transposed trampoline slot is visible.
 *
 * `reg_fixed` / `reg_out` pin registers to a value; `reg_same` requires them to
 * come back as they went in.  A register in neither mask is not checked -- the
 * specification says nothing about it, and the harness must not invent claims.
 * RSP is never checked: the harness owns the stack.
 *
 * `flag_fixed` / `flag_val` and `flag_same` are the same split over flags, and
 * are applied under each rflags seed the harness runs.
 */
"""


def flagmask(flags) -> str:
    return " | ".join("FLAG_" + f for f in flags) if flags else "0"


def c_case(t) -> str:
    reg_in = [M.filler(i) for i in range(16)]
    for reg, v in t.pre:
        reg_in[M.REGS.index(reg)] = v

    reg_out = [0] * 16
    reg_fixed, reg_same = 0, 0
    flag_fixed, flag_val, flag_same = [], [], []
    for c in t.post:
        if isinstance(c, M.Reg):
            i = M.REGS.index(c.reg)
            reg_fixed |= 1 << i
            reg_out[i] = c.value
        elif isinstance(c, M.RegsSame):
            reg_same = 0xffff
        elif isinstance(c, M.FlagsSame):
            flag_same = list(M.FLAGS)
        elif isinstance(c, M.Flag):
            flag_fixed.append(c.flag)
            if c.on:
                flag_val.append(c.flag)
        elif isinstance(c, M.FlagSame):
            flag_same.append(c.flag)
    reg_same &= ~reg_fixed & 0xffff

    def quads(vs):
        return "\n".join("      0x%016xull, 0x%016xull, 0x%016xull, 0x%016xull,"
                          % tuple(vs[i:i + 4]) for i in range(0, 16, 4))

    out = ['  { .name = "%s", .disasm = "%s",' % (t.name, t.disasm),
           "    .code = code_%s, .code_len = %d," % (t.name, len(t.code)),
           "    .reg_in = {", quads(reg_in), "    },"]
    if reg_fixed:
        out += ["    .reg_fixed = 0x%04x, .reg_out = {" % reg_fixed, quads(reg_out), "    },"]
    if reg_same:
        out.append("    .reg_same = 0x%04x," % reg_same)
    out.append("    .flag_fixed = %s, .flag_val = %s, .flag_same = %s },"
               % (flagmask(flag_fixed), flagmask(flag_val), flagmask(flag_same)))
    return "\n".join(out)


def generate_cases() -> str:
    parts = [C_PREAMBLE]
    for t in M.TESTS:
        parts.append("static const uint8_t code_%s[] = {%s};"
                     % (t.name, ", ".join("0x%02x" % b for b in t.code)))
    parts.append("")
    parts.append("static const test_case CASES[] = {")
    for t in M.TESTS:
        parts.append(c_case(t))
    parts += ["};", ""]
    return "\n".join(parts)


def generate_disasm() -> str:
    """The listing `check_disasm.py` holds objdump to.

    Written here rather than seeded from objdump's own output, so that it says
    what the manifest claims the bytes mean, not what the decoder happened to
    say.  Otherwise agreement would be guaranteed and the check vacuous.
    """
    import check_disasm
    return check_disasm.listing_expected()


TARGETS = ((MM0, generate_mm0), (CASES, generate_cases), (DISASM, generate_disasm))


def validate():
    seen = set()
    for t in M.TESTS:
        if t.name in seen:
            raise SystemExit("duplicate test name: %s" % t.name)
        seen.add(t.name)
        if not 1 <= len(t.code) <= 15:
            raise SystemExit("%s: instruction length %d out of range"
                             % (t.name, len(t.code)))
        regs = [r for r, _ in t.pre]
        regs += [c.reg for c in t.post if isinstance(c, M.Reg)]
        for r in regs:
            if r not in M.REGS:
                raise SystemExit("%s: unknown register %s" % (t.name, r))
            i = M.REGS.index(r)
            if i == M.RSP:
                raise SystemExit("%s: RSP is not testable -- the harness owns "
                                 "the stack" % t.name)
            if i >= M.REGS_NAMED_IN_MM0:
                raise SystemExit("%s: %s has no def in x86.mm0, so it cannot "
                                 "appear in a statement" % (t.name, r))
        for c in t.post:
            f = getattr(c, "flag", None)
            if f is not None and f not in M.FLAG_BIT:
                raise SystemExit("%s: %s is not modelled by x86.mm0" % (t.name, f))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true",
                   help="do not write; fail if a committed file is stale")
    args = p.parse_args()
    validate()

    stale = False
    for path, gen in TARGETS:
        new = gen()
        rel = path.relative_to(HERE)
        if not args.check:
            path.parent.mkdir(exist_ok=True)
            path.write_text(new)
            print("wrote %s" % rel)
            continue
        old = path.read_text() if path.exists() else ""
        if old == new:
            print("%s is up to date" % rel)
            continue
        stale = True
        sys.stdout.writelines(difflib.unified_diff(
            old.splitlines(True), new.splitlines(True),
            fromfile="%s (committed)" % rel, tofile="%s (from manifest)" % rel))
        print("\n%s is stale; run ./gen.py" % rel, file=sys.stderr)
    print("%d tests" % len(M.TESTS))
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
